stages:
  - test

cache:
  paths:
    - /var/cache/apt/archives

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - true

test:php-7.2:
  stage: test
  image: php:7.2
  script:
    - true
  tags:
    - sdo
