name: Unit tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['8.2']

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, dom, fileinfo # Add your extensions here.
          coverage: xdebug
      - name: Run Tests
        run: ./bin/prepare_tests.sh && ./bin/run_tests.sh
